### ISSUE TITLE
Load empty chunk

### ISSUE THREAD

**Issue by cmpute** [sergkr/gltflib#1]
I'm trying to load the glb files from [this repo](https://github.com/uber/xviz-data), and specifically when I try to load [1-frame.glb](https://github.com/uber/xviz-data/blob/master/kitti/2011_09_26_drive_0005_sync/1-frame.glb), the library says "Binary chunk body may not be empty". Is there any reason not allowing binary chunk to be empty? And how can I load the data in that repo properly?

**Comment by sergkr** [comment]
Thanks for bringing up this issue. I checked the spec, and I'm not seeing anything in there that specifically prohibits a binary chunk with a zero byte length. So I think that check can be safely removed. I probably put that in there as a safeguard. Which sounded reasonable, but if there are valid models floating around that can't be loaded as a result, then all the more reason to remove it. I'll put up a new version soon.

**Comment by sergkr** [comment]
I just put out version 1.0.2, which allows empty body in a binary chunk. Closing this issue as fixed.

There are other issues with the file you linked from uber's repo (`1-frame.glb`) which prevent it from loading. However, those issues appear to be with the file itself. The official [glTF validator](https://github.khronos.org/glTF-Validator/) summarizes those pretty well - basically they're not labeling [chunk types](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#binary-gltf-layout) correctly (all nulls, should be either `JSON` or `BIN`), and missing padding. I'm not even sure how to interpret the bytes at the end - those might have been incorrect padding, or just garbage data. For what it's worth, I wasn't able to load that file with any glTF viewer either.

**Comment by cmpute** [comment]
Thanks!
