### ISSUE TITLE
MIME type should be copied from FileResource as well

### ISSUE THREAD

**Issue by alexey-pelykh** [sergkr/gltflib#123]
https://github.com/sergkr/gltflib/blob/748322d10f6abb412e0814360a40939774f2644a/gltflib/gltf.py#L659

**Comment by alexey-pelykh** [comment]
Addressed by https://github.com/sergkr/gltflib/pull/124

**Comment by sergkr** [comment]
Fixed and released as [v1.0.8](https://github.com/sergkr/gltflib/releases/tag/v1.0.8). Thank you!
