### ISSUE TITLE
Is it possible to get the face number of the gltf model and how to get it?

### ISSUE THREAD

**Issue by ShoutTree** [sergkr/gltflib#153]
Hi, sergkr
I wonder if it's possible to get the face number of the gltf model after loading it from file, and if it's possible how to do that?
Thanks

**Comment by sergkr** [comment]
Hi @ShoutTree - not sure what you mean exactly. A glTF model can consist of multiple scenes, each of which may have multiple nodes, which may contain multiple meshes, which may have multiple primitives. It's when you get to the primitive level that the concept of face numbers starts to make sense. In any case, this library isn't really aimed at working with the geometry - you may want to check out the [trimesh](https://github.com/mikedh/trimesh) library (specifically the [trimesh.exchange.gltf](https://trimsh.org/trimesh.exchange.gltf.html) module) for that.
