### ISSUE TITLE
URI-encoded spaces are not supported

### ISSUE THREAD

**Issue by alexey-pelykh** [sergkr/gltflib#162]
See https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box%20With%20Spaces

**Comment by alexey-pelykh** [comment]
Details here https://github.com/KhronosGroup/glTF/issues/1449

**Comment by sergkr** [comment]
Sorry for the delay - I was moving across the country!

This (along with your other 2 PRs) have just been released as [v1.0.10](https://github.com/sergkr/gltflib/releases/tag/v1.0.10).

**Comment by alexey-pelykh** [comment]
Thanks!
