### ISSUE TITLE
Sampler type in animation.py should be AnimationSampler

### ISSUE THREAD

**Issue by totex** [sergkr/gltflib#3]
Hello Sergey!
In the animation.py the sampler type is not correct:
`samplers: List[Sampler] = None`
This loads the texture sampler data:
```
"samplers": [
        {
            "magFilter": 9729,
            "minFilter": 9986,
            "wrapS": 10497,
            "wrapT": 10497
        }
```
The line should be changed to :
`samplers: List[AnimationSampler] = None`
So it loads the correct data:
```
"samplers": [
                {
                    "input": 6,
                    "interpolation": "LINEAR",
                    "output": 7
                },
```

**Comment by sergkr** [comment]
Hey there, thanks for reporting this. Sorry it took me a while to get to the other one (#2), but both issues have now been fixed, and a new version has been released just now that includes these fixes (v1.0.3). I'm going to work on adding some roundtrip tests against all the official [sample models repo](https://github.com/KhronosGroup/glTF-Sample-Models) to ensure I didn't miss anything else. There are some areas of the spec I haven't looked at very closely as I didn't need them for my purposes (including both skins and animations) - but I do want to make sure these are all properly supported. Thanks again, and don't hesitate to open another issue if you encounter anything else in the meantime!
